devel: Check to see that you've sourced the env

diff --git a/devel/env b/devel/env
--- a/devel/env
+++ b/devel/env
@@ -14,4 +14,10 @@ DATASETS="state-papers fine-rolls"
 # eg. 4 on a 2011 MacBook Air)
 JOBS=8
 
+which mk-report.py
+if [ $? -ne 0 ]; then
+    echo >&2 "Can't find mk-report.py"
+    echo >&2 "Did you activate your virtual environement?"
+    exit 1
+fi
 # vim:set syntax=sh
